spring:
  application:
    name: Travelbook-33

  datasource:

#    url: jdbc:postgresql://localhost:5432/travelbook_33
#    username: postgres
#    password: qwerty007

    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

  web:
    resources:
      static-locations: file:./uploads/

  http:
   multipart:
     max-file-size: 500MB
     max-request-size: 500MB

jwt:
  secret: 'fckxnmhXT1dJznQqwL6oAZdnr7U6jPYXxeA28YTMf9w='  # Замените на ваш сгенерированный ключ
  expiration: 3600000  # Пример: время истечения токена в миллисекундах (1 час)

server:
  port: 8080  # Убедитесь, что этот порт совпадает с тем, на котором приложение работает
  address: 0.0.0.0
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.example: DEBUG

#file:
#  upload-dir: D:/IT/Travelbook_33B/backend/uploads

file:
  upload-dir: /path/to/uploads

