spring:
  application:
    name: Travelbook-33

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

jwt:
  secret: 'fckxnmhXT1dJznQqwL6oAZdnr7U6jPYXxeA28YTMf9w='  # Замените на ваш сгенерированный ключ
  expiration: 3600000  # Пример: время истечения токена в миллисекундах (1 час)

server:
  port: 8080  # Убедитесь, что этот порт совпадает с тем, на котором приложение работает
  address: 0.0.0.0
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.example: DEBUG
